import React from 'react';
import { Text } from 'react-native';
import styles from './testStyles';

interface TestProps {}

const Test: React.FC<TestProps> = () => {
  return (
    <>
      <Text style={{ color: 'white' }}>This is a component generated by component.py</Text>
    </>
  );
};

export default Test;
