name: Build Android

on:
  # pull_request:
  #   branches:
  #     - main
  #   paths:
  #     - 'app/src/**'
  push

jobs:
  iOS-Build:
    name: Build Android
    runs-on: [self-hosted, windows]
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Cancel Incomplete Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@master
        
      - name: Install node modules
        run: |
          yarn install

      - name: Clean and Build For Android
        run: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease
