name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  iOS-Build:
    name: Build iOS
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@master
        
      - name: Install node modules
        run: |
          yarn install
      
      - name: Install pods
        run: |
          cd ios
          bundle install
          cd ..
          yarn install:pods

      - name: Build For iOS
        run: |
          yarn ios

      - name: Clean Up
        if: always()
        run: | 
          echo "Cleaning up"
          xcrun simctl shutdown all && xcrun simctl erase all
