name: Continuous Integration

on:
  push:
    branches:
      - feature/ci-script

jobs:
  iOS-Build:
    name: Test
    runs-on: macOS-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0.2'

      - uses: actions/setup-node@master
      - uses: c-hive/gha-yarn-cache@v2
        with:
          directory: ./app
        
      - name: Install node modules
        run: |
          yarn install

      - name: Run Jest Tests
        run: |
          yarn test
      
      - name: Install pods
        run: |
          yarn install:pods

      - name: Build For iOS
        run: |
          yarn ios
