name: CI
on: push
jobs:
  build:
    defaults:
        run:
          working-directory: ./app
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test